import type { Metadata } from "next";
import { Lora, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

// Define Google Fonts
const lora = Lora({ subsets: ["latin"], weight: ["400", "500", "700", "600"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900", "100"],
});

export const metadata: Metadata = {
  title: "Narratiq - Welcome to the book world",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className} ${roboto.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
