const quotes = [
    "The only way to do great work is to love what you do. — Steve Jobs",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. — Martin Luther King Jr.",
    "The best way to predict the future is to invent it. — Alan Kay",
    "Life is what happens when you're busy making other plans. — John Lennon",
    "It does not matter how slowly you go as long as you do not stop. — Confucius",
    "You must be the change you wish to see in the world. — Mahatma Gandhi",
    "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. — Albert Schweitzer",
    "Your time is limited, don’t waste it living someone else’s life. — Steve Jobs",
    "Believe you can and you're halfway there. — Theodore Roosevelt",
    "The journey of a thousand miles begins with one step. — Lao Tzu",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
    "You miss 100% of the shots you don’t take. — Wayne Gretzky",
    "The only thing we have to fear is fear itself. — Franklin D. Roosevelt",
    "Happiness is not something ready made. It comes from your own actions. — Dalai Lama",
    "Act as if what you do makes a difference. It does. — William James",
    "The mind is everything. What you think you become. — Buddha",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson",
    "You do not find the happy life. You make it. — Camilla E. Kimball",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. — Winston Churchill",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
    "Don’t watch the clock; do what it does. Keep going. — Sam Levenson",
    "It is never too late to be what you might have been. — George Eliot",
    "Everything you’ve ever wanted is on the other side of fear. — George Addair",
    "The only impossible journey is the one you never begin. — Tony Robbins",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
    "It does not matter how many times you get knocked down, but how many times you get up. — Vince Lombardi",
    "Perseverance is not a long race; it is many short races one after the other. — Walter Elliot",
    "Success is the sum of small efforts, repeated day in and day out. — Robert Collier",
    "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. — Vince Lombardi",
    "Great things are not done by impulse, but by a series of small things brought together. — Vincent Van Gogh",
    "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
    "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
    "Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman",
    "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
    "The harder you work for something, the greater you’ll feel when you achieve it. — Unknown",
    "The only way to achieve the impossible is to believe it is possible. — Charles Kingsleigh",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently. — Marie Forleo",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. — Roy T. Bennett",
    "You don’t have to be great to start, but you have to start to be great. — Zig Ziglar",
    "Perseverance is failing 19 times and succeeding the 20th. — Julie Andrews",
    "The secret of success is constancy to purpose. — Benjamin Disraeli",
    "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway. — Earl Nightingale",
    "You don’t have to be perfect to be amazing. — Unknown",
    "Difficulties in life are intended to make us better, not bitter. — Dan Reeves",
    "With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
    "Don’t let yesterday take up too much of today. — Will Rogers",
    "You are braver than you believe, stronger than you seem, and smarter than you think. — A.A. Milne",
    "Success is not how high you have climbed, but how you make a positive difference to the world. — Unknown",
    "The best way to predict your future is to create it. — Peter Drucker",
    "You don’t have to see the whole staircase, just take the first step. — Martin Luther King Jr.",
    "Don’t be discouraged. It’s often the last key in the bunch that opens the lock. — Unknown",
    "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
    "The path to success is to take massive, determined action. — Tony Robbins",
    "Success is not for the chosen few, but for the few who choose it. — Unknown",
    "Your limitation—it's only your imagination. — Unknown",
    "Push yourself, because no one else is going to do it for you. — Unknown",
    "Great things never come from comfort zones. — Unknown",
    "Dream it. Wish it. Do it. — Unknown",
    "Success doesn’t just find you. You have to go out and get it. — Unknown",
    "Dream bigger. Do bigger. — Unknown",
    "Don’t stop when you’re tired. Stop when you’re done. — Unknown",
    "Wake up with determination. Go to bed with satisfaction. — Unknown",
    "The key to success is to focus on goals, not obstacles. — Unknown",
    "Hard work beats talent when talent doesn’t work hard. — Tim Notke",
    "Don’t wait for opportunity. Create it. — Unknown",
    "Success is not measured by what you accomplish, but the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds. — Orison Swett Marden",
    "Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun",
    "The difference between a successful person and others is how long they spend feeling sorry for themselves. — Unknown",
    "Dreams don’t work unless you do. — John C. Maxwell",
    "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
    "Success doesn’t happen overnight. It takes hard work, dedication, and perseverance. — Unknown",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. — William James",
    "You’re never a loser until you quit trying. — Mike Ditka",
    "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
    "If you want to achieve greatness stop asking for permission. — Unknown",
    "Success is the result of preparation, hard work, and learning from failure. — Colin Powell",
    "Every accomplishment starts with the decision to try. — John F. Kennedy",
    "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
    "The only person you should try to be better than is the person you were yesterday. — Unknown",
    "The future depends on what you do today. — Mahatma Gandhi",
    "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
    "The best preparation for tomorrow is doing your best today. — H. Jackson Brown Jr.",
    "Opportunities don't happen, you create them. — Chris Grosser",
    "Success is not just about making money. It’s about making a difference. — Unknown",
    "Success is liking yourself, liking what you do, and liking how you do it. — Maya Angelou",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. — Steve Jobs",
    "You only live once, but if you do it right, once is enough. — Mae West",
    "Don’t count the days, make the days count. — Muhammad Ali",
    "Be yourself; everyone else is already taken. — Oscar Wilde",
    "The purpose of our lives is to be happy. — Dalai Lama",
    "We can't help everyone, but everyone can help someone. — Ronald Reagan",
    "The only way to achieve the impossible is to believe it is possible. — Charles Kingsleigh"
];

export default quotes;
